FROM golang:1.24-alpine AS builder
ENV GOPROXY=https://goproxy.cn,direct
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache clang llvm-dev libbpf-dev linux-headers
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go generate ./cmd/tracer/...
RUN CGO_ENABLED=0 go build -o /tracer ./cmd/tracer/

FROM alpine:3.19
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache libbpf
COPY --from=builder /tracer /usr/local/bin/tracer
ENTRYPOINT ["/usr/local/bin/tracer"]